### ISSUE TITLE
user-profile

### ISSUE THREAD

**Issue by zenesys0081** [zenesys0069/zenvid-apis#5]
Endpoints :- /user/profile
   a) add the user popular videos likes.
   b) add the user description.
   c) add unfollow option api .(multiple time follow same user.)

**Comment by akshaymemail** [comment]
loggged in user video api is already there, please check below endpoint.

endpoint : /user/videos

**Comment by akshaymemail** [comment]
1. Added 'description' for user
2. Fixed where user was able to follow to self
3. Fixed where user was able to follow multiple times
